### ISSUE TITLE
Add more XDMA channels

### ISSUE THREAD

**Issue by iomartin** [Eideticom/eid-hermes-qemu#9]
The XDMA specification and driver support up to 4 DMA channels in each direction, but the Hermes QEMU device currently only supports one in each direction.

To support the extra channels, we probably just need to:
1. Initialize the appropriate H2C/C2H registers. See on Table 36 of the [XDMA spec](https://www.xilinx.com/support/documentation/ip_documentation/xdma/v4_1/pg195-pcie-dma.pdf) how the BAR addresses are defined. Bits 11:8 define the channel. We probably only need the identifier and alignment registers to start with (0x00 and 0x4C respectively).
2. Update the BAR2 read/write functions to handle the new channels.
3. Implement the QEMU logic to handle the extra channels. So adding extra threads, mutex, etc.

If all works out, the new channels would show up as `/dev/xdma0_{c2h,h2c}_{0,1,2,3}` and we should be able to use them with this [test example](https://github.com/aws/aws-fpga/tree/master/sdk/linux_kernel_drivers/xdma#quick-example).

**Comment by niclashedam** [comment]
I'll like to give this issue a go. Can you assign it to me?

**Comment by niclashedam** [comment]
I have a few questions that I would like answered before proceeding with subtask 1. Is it correct that what needs to be done, in essence, is converting the `HermesState->bar2` member to an array containing 4 `bar2` structs? Is it correct that the initialisation should be done in `hermes_instance_init`?

**Comment by iomartin** [comment]
Hi @niclashedam,

1. No. BAR2 (`HermesState->bar2`) contains other registers that aren't replicated for multiple channels (the `hermes_bar2_irq_reg` and `hermes_bar2_cfg_reg`). It would be better to convert the `h2c` and `c2h` members of the `struct hermes_bar2` struct to arrays. Something like this:

```C
struct hermes_bar2 {                                                             
    struct hermes_bar2_dir_reg h2c[H2C_CHANNELS];
    struct hermes_bar2_dir_reg c2h[C2H_CHANNELS];
    struct hermes_bar2_irq_reg irq;
    struct hermes_bar2_cfg_reg cfg;
};
```

2. Yes, I would suggest that we init them on `hermes_instance_init`, but I'd also use a couple of `static const struct hermes_bar2_dir_reg` global variables which initialize a single c2h/h2c channel each, so then we can memcpy them during `hermes_instance_init`.
